"use strict";const amountSlider=document.getElementById("myAmount");const amountInput=document.getElementById("inputAmount");const stepUpSlider=document.getElementById("stepUpSlider");const stepUpInput=document.getElementById("stepUpInput");const roiSlider=document.getElementById("myRoi");const roiInput=document.getElementById("inputRoi");const tenureSlider=document.getElementById("myYears");const tenureInput=document.getElementById("inputYears");const heading=document.getElementById("heading");const amountLabel=document.getElementById("amount");const textTotalInvestment=document.getElementById("r1");const textWealthGained=document.getElementById("r2");const textTotalReturns=document.getElementById("r3");let initialLoad=true;let calculatorMode;let chart;const calcModes={SIP:"sip",LUMPSUM:"lumpsum",STEPUP:"stepup",};AttachInputListeners();getParams();changeMode(calculatorMode);function changeMode(mode){calculatorMode=mode;const stepUpInputDiv=document.getElementById("stepUpInputDiv");if(mode===calcModes.SIP){document.getElementById("radio-1").checked=true;stepUpInputDiv.style.display="none";heading.innerHTML="SIP Calculator";amountLabel.innerHTML="Monthly Investment";}else if(mode===calcModes.LUMPSUM){document.getElementById("radio-2").checked=true;stepUpInputDiv.style.display="none";heading.innerHTML="Lumpsum Calculator";amountLabel.innerHTML="Total Investment";}else if(mode===calcModes.STEPUP){const radioDiv=document.getElementById('radioDiv');radioDiv.style.display="none";stepUpInputDiv.style.display="block";heading.innerHTML="Step Up SIP Calculator";}
calculate();}
function calculate(){const amount=Number(amountInput.value);const roi=Number(roiInput.value);const tenure=Number(tenureInput.value);const stepUp=Number(stepUpInput.value);if(calculatorMode===calcModes.SIP){calculateSipReturns(amount,roi,tenure);}else if(calculatorMode===calcModes.LUMPSUM){calculateLumpsumReturns(amount,roi,tenure);}else if(calculatorMode===calcModes.STEPUP){calculateStepUpSipReturns(amount,roi,tenure,stepUp);}}
function calculateSipReturns(amount,roi,tenure){if(amount>=500&&roi>=1){const MonthlyROI=roi/(100*12);const months=tenure*12;const totalReturns=Math.round(amount*((Math.pow(1+MonthlyROI,months)-1)/MonthlyROI)*(1+MonthlyROI));const totalInvestment=amount*tenure*12;const wealthGained=totalReturns-totalInvestment;generateChart(totalInvestment,wealthGained);textTotalInvestment.innerHTML="₹"+totalInvestment.toLocaleString("en-IN");textWealthGained.innerHTML="₹"+wealthGained.toLocaleString("en-IN");textTotalReturns.innerHTML="₹"+totalReturns.toLocaleString("en-IN");}}
function calculateLumpsumReturns(amount,roi,tenure){if(amount>=500&&roi>=1){const totalReturns=Math.round(Math.pow(1+roi/100,tenure)*amount);const totalInvestment=amount;const wealthGained=totalReturns-totalInvestment;generateChart(totalInvestment,wealthGained);textTotalInvestment.innerHTML="₹"+totalInvestment.toLocaleString("en-IN");textWealthGained.innerHTML="₹"+wealthGained.toLocaleString("en-IN");textTotalReturns.innerHTML="₹"+totalReturns.toLocaleString("en-IN");}}
function calculateStepUpSipReturns(amount,roi,tenure,stepUp){if(amount>=500&&roi>=1&&stepUp>=1){const initialAmount=amount;const roiInDecimal=roi/100;const stepUpInDecimal=stepUp/100;const tenureInMonths=tenure*12;let increasedSipAmount=amount;let totalInvestment=amount*12;const monthsInYear=12;let totalReturns=0;for(let i=1;i<=monthsInYear;i++){totalReturns=totalReturns+initialAmount*Math.pow((1+roiInDecimal/12),tenureInMonths-i+1);}
for(let i=2;i<=tenure;i++){increasedSipAmount=increasedSipAmount+increasedSipAmount*stepUpInDecimal;totalInvestment=totalInvestment+increasedSipAmount*12;for(let j=1;j<=monthsInYear;j++){const currentMonth=i*12+1;totalReturns=totalReturns+increasedSipAmount*Math.pow((1+roiInDecimal/12),tenureInMonths-currentMonth+1);}}
const wealthGained=totalReturns-totalInvestment;generateChart(totalInvestment.toFixed(2),wealthGained.toFixed(2));const results={totalInvestment,wealthGained,totalReturns}
const finalResult=formatNumber(results);textTotalInvestment.innerHTML="₹"+finalResult.totalInvestment
textWealthGained.innerHTML="₹"+finalResult.wealthGained;textTotalReturns.innerHTML="₹"+finalResult.totalReturns;}}
function formatNumber(resultObj){let totalInvestment=resultObj.totalInvestment;let totalReturns=resultObj.totalReturns;let wealthGained=resultObj.wealthGained;const oneCrore=10000000;if(totalInvestment>oneCrore){totalInvestment=Number((totalInvestment/oneCrore).toFixed(2));totalInvestment=totalInvestment.toLocaleString("en-IN")+' Cr';}else{totalInvestment=(Math.round(totalInvestment)).toLocaleString('en-IN');}
if(totalReturns>oneCrore){totalReturns=Number((totalReturns/oneCrore).toFixed(2));totalReturns=totalReturns.toLocaleString("en-IN")+' Cr';}else{totalReturns=(Math.round(totalReturns)).toLocaleString('en-IN');}
if(wealthGained>oneCrore){wealthGained=Number((wealthGained/oneCrore).toFixed(2));wealthGained=wealthGained.toLocaleString("en-IN")+' Cr';}else{wealthGained=(Math.round(wealthGained)).toLocaleString('en-IN');}
const results={totalInvestment,totalReturns,wealthGained}
return results;}
function DrawChart(investedAmountVal,wealthGainedVal){var ctx=document.getElementById("myChart").getContext("2d");chart=new Chart(ctx,{type:"doughnut",data:{labels:["Invested Amount","Est. Returns"],datasets:[{backgroundColor:["#5367ff","#00d09c"],data:[investedAmountVal,wealthGainedVal],},],},options:{segmentShowStroke:false,responsive:true,},});}
function generateChart(investedAmountVal,wealthGainedVal){if(!initialLoad){chart.destroy();}
DrawChart(investedAmountVal,wealthGainedVal);initialLoad=false;}
function getParams(){let urlVal=window.location.href;let url=new URL(urlVal);let cta=url.searchParams.get("cta");let mode=url.searchParams.get("mode");let logo=url.searchParams.get("logo");if(mode==="lumpsum"){calculatorMode="lumpsum";}else if(mode==="stepup"){calculatorMode="stepup";}else{calculatorMode="sip";}
if(cta==="hide"){let ctaDiv=document.getElementById("cta");ctaDiv.style.display="none";}
if(logo==="true"){document.getElementById("logo").style.display="block";}}
function AttachInputListeners(){amountSlider.addEventListener("input",(e)=>{amountInput.value=e.target.value;calculate();});stepUpSlider.addEventListener("input",(e)=>{stepUpInput.value=e.target.value;calculate();});roiSlider.addEventListener("input",(e)=>{roiInput.value=e.target.value;calculate();});tenureSlider.addEventListener("input",(e)=>{tenureInput.value=e.target.value;calculate();});amountInput.addEventListener("input",(e)=>{let value=Number(e.target.value);amountSlider.value=value;if(value<0){amountInput.value=500;}else if(value>200000){amountInput.value=200000;}
calculate();});stepUpInput.addEventListener("input",(e)=>{const value=Number(e.target.value);stepUpSlider.value=value;if(value<0){stepUpInput.value=1;}else if(value>50){stepUpInput.value=50;}
calculate();});roiInput.addEventListener("input",(e)=>{let value=Number(e.target.value);roiSlider.value=value;if(value<0){roiInput.value=1;}else if(value>30){roiInput.value=30;}
calculate();});}