baseURL: https://Fincz.com
title: Fincz Finance Blog
theme: hugo-theme-bootstrap
copyright: Copyright © 2020-{year} Fincz. All Rights Reserved.

# Multilingual mode
defaultContentLanguage: en
defaultContentLanguageInSubdir: false
#disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw

pagination:
  pagerSize: 10

# Disqus
# disqusShortname: yourdiscussshortname

# Google Analytics
googleAnalytics: G-SP0MLCNXK8

enableRobotsTXT: true
enableEmoji: true
# hasCJKLanguage: true

pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

mediaTypes:
  application/manifest+json:
    suffixes:
      - json

outputFormats:
  MANIFEST:
    name: manifest
    baseName: manifest
    mediaType: application/manifest+json

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - MANIFEST

taxonomies:
  category: categories
  series: series
  tag: tags

# sitemap:
#   changefreq: monthly
#   filename: sitemap.xml
#   priority: 0.5

permalinks:
  posts: /:contentbasename/

markup:
  goldmark:
    renderer:
      unsafe: true
