baseURL: "https://learn.fincz.com/"
title: "Fincz Learn"
theme: hugo-theme-bootstrap
copyright: Copyright © 2020-{year} Fincz Learn. All Rights Reserved.

# Multilingual mode
defaultContentLanguage: en
defaultContentLanguageInSubdir: false

pagination:
  pagerSize: 10

# Google Analytics
googleAnalytics: G-PQYJ3GVSRZ

enableRobotsTXT: true
enableEmoji: true

pygmentsUseClasses: true

blackfriday:
  hrefTargetBlank: true

mediaTypes:
  application/manifest+json:
    suffixes:
      - json

outputFormats:
  MANIFEST:
    name: manifest
    baseName: manifest
    mediaType: application/manifest+json

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - MANIFEST

taxonomies:
  category: categories
  series: series
  tag: tags

permalinks:
  guides: /guides/:slug/
  practice: /practice/:slug/
  notes: /notes/:slug/
  posts: /:slug/

markup:
  goldmark:
    renderer:
      unsafe: true

build:
  writeStats: true
  writeDebug: true