[en]
  languageName = "English"
  weight = 1
  contentDir = "content/en"

[hi]
  languageName = "हिंदी"
  weight = 2
  contentDir = "content/hi"
  [hi.params]
    description = "Fincz Finance Blog in Hindi"
    #keywords = "Fashion, makeup guide"
    [pwa]
      [pwa.manifest]
