[[main]]
  name = "Finance"
  identifier = "Finance"
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
  url = '/categories/finance/'

#
#[[main]]
#  id = "github"
#  parent = "blogging"
# url = "https://github.com/razonyang/hugo-theme-bootstrap"
#  pre = '<i class="fab fa-fw fa-github"></i>'
#

[[footer]]
  identifier = "home"
  name = "Home"
  url = "/"

[[footer]]
  identifier = "about"
  name = "About"
  url = "/about/"

[[footer]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"

[[footer]]
  identifier = "privacy-policy"
  name = "Privacy Policy"
  url = "/privacy-policy/"

[[footer]]
  identifier = "copy-right"
  name = "Copy Right"
  url = "/copy-right/"

[[footer]]
  identifier = "disclaimer"
  name = "Disclaimer"
  url = "/disclaimer/"

[[footer]]
  identifier = "terms-and-conditions"
  name = "Terms and Conditions"
  url = "/terms-and-conditions/"


  [[footer]]
  identifier = "amazon affiliate disclosure"
  name = "Amazon Affiliate Disclosure"
  url = "/amazon-affiliate-disclosure/"