[[main]]
  name = "Finance"
  identifier = "Finance"
  pre = '<i class="fas fa-fw fa-chevron-circle-down"></i>'
  url = '/categories/finance/'

[[main]]
  name = "Tools"
  identifier = "Tools"
  pre = '<i class="fas fa-fw fa-chevron-circle-up"></i>'
  url = '/categories/tools/'

[[footer]]
  identifier = "quick-links"
  name = "Quick Links"
  weight = 1

[[footer]]
  identifier = "home"
  name = "Home"
  url = "/"
  parent = "quick-links"
  weight = 1

[[footer]]
  identifier = "about"
  name = "About"
  url = "/about/"
  parent = "quick-links"
  weight = 2

[[footer]]
  identifier = "contact"
  name = "Contact"
  url = "/contact/"
  parent = "quick-links"
  weight = 3

[[footer]]
  identifier = "others-links"
  name = "Others Links"
  weight = 2

[[footer]]
  identifier = "privacy-policy"
  name = "Privacy Policy"
  url = "/privacy-policy/"
  parent = "others-links"
  weight = 1

[[footer]]
  identifier = "copy-right"
  name = "Copy Right"
  url = "/copy-right/"
  parent = "others-links"
  weight = 2

[[footer]]
  identifier = "terms-and-conditions"
  name = "Terms and Conditions"
  url = "/terms-and-conditions/"
  parent = "others-links"
  weight = 3

  [[footer]]
  identifier = "amazon affiliate disclosure"
  name = "Amazon Affiliate Disclosure"
  url = "/amazon-affiliate-disclosure/"
  parent = "others-links"
  weight = 4

[[footer]]
  identifier = "favorite-sites"
  name = "Favorite Sites"
  weight = 3

[[footer]]
  identifier = "theislah"
  name = "Theislah"
  url = "https://theislah.com"
  parent = "favorite-sites"
  weight = 1

[[footer]]
  identifier = "bestrani"
  name = "Bestrani"
  url = "https://bestrani.com"
  parent = "favorite-sites"
  weight = 2

[[footer]]
  identifier = "itechf"
  name = "Itechf"
  url = "https://itechf.com"
  parent = "favorite-sites"
  weight = 3

[[footer]]
  identifier = "dqote"
  name = "Dqote"
  url = "https://dqote.com"
  parent = "favorite-sites"
  weight = 4