email = "fincz.it@gmail.com"
facebook = "Share-Market-123554999895949"
# github = "yourgithubusername"
# gitlab = "yourgitlabusername"
# linkedin = "yourlinkedinusername"
# stackoverflow = "yourstackoverflowuserid"
twitter = "fincz1"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
# instagram = "best.rani"
# quora = "Iffat-Zia-3"
# tumblr = "bestrani-t"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
# medium = "bestrani" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
youtube = "UCZazdfaoIu9trcSF2b6_7MQ"
# discord = "yourdiscordinvitecode"
# discourse = "https://yourforum.tld"
# facebookgroup = "yourfacebookgroupname"
# Pinterest = "bestraniP"
