email = "bestrani.e@hotmail.com"
facebook = "BestRaniP"
# github = "yourgithubusername"
# gitlab = "yourgitlabusername"
# linkedin = "yourlinkedinusername"
# stackoverflow = "yourstackoverflowuserid"
 twitter = "@BestRani3"
# weibo = "yourweibousername"
# zhihu = "yourzhihuusername"
 instagram = "best.rani"
 quora = "Iffat-Zia-3"
 tumblr = "bestrani-t"
# reddit = "yourredditusername"
# telegram = "yourtelegramusername"
# qq = "yourqqnumber"
# dockerhub = "yourdockerhubusername"
# bitbucket = "yourbitbucketworkspaceid"
 medium = "bestrani" # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm = "yourlastfmusername"
# bilibili = "yourbilibiliuserid"
# youtube = "UCfgmG1A2Za-nU5R6rFv7q1g"
# discord = "yourdiscordinvitecode"
# discourse = "https://yourforum.tld"
# facebookgroup = "yourfacebookgroupname"
# Pinterest = "bestraniP"
