"use strict";var sliderMI=document.getElementById("sliderMI");var inputMI=document.getElementById("inputMI");var sliderROI=document.getElementById("sliderROI");var inputROI=document.getElementById("inputROI");var sliderTenure=document.getElementById("sliderTenure");var inputTenure=document.getElementById("inputTenure");var tpMode=document.getElementById("tp_mode");inputMI.innerHTML=sliderMI.value;inputROI.innerHTML=sliderROI.value;inputTenure.innerHTML=sliderTenure.value;sliderMI.oninput=function(){inputMI.innerHTML=this.value;};sliderROI.oninput=function(){inputROI.innerHTML=this.value;};sliderTenure.oninput=function(){inputTenure.innerHTML=this.value;};function showTotalInvestmentVal(newVal){sliderMI.value=newVal;calculateIt();}
function showExpectedReturnsVal(newVal){sliderROI.value=newVal;calculateIt();}
function showTimePeriodVal(newVal){sliderTenure.value=newVal;calculateIt();}
sliderMI.addEventListener("input",updateValueTotalInvestment);sliderROI.addEventListener("input",updateValueExpectedReturns);sliderTenure.addEventListener("input",updateValueTimePeriod);function updateValueTotalInvestment(e){inputMI.value=e.srcElement.value;calculateIt();}
function updateValueExpectedReturns(e){inputROI.value=e.srcElement.value;calculateIt();}
function updateValueTimePeriod(e){inputTenure.value=e.srcElement.value;calculateIt();}
AttachInputListeners();var initialLoad=true;var chart;getParams();calculateIt();function calculateIt(){let O_TI=document.getElementById("r1");let O_ER=document.getElementById("r2");let O_MV=document.getElementById("r3");let TI,ER,MV;let MI=Number(inputMI.value);let ROI=Number(inputROI.value);let T=Number(inputTenure.value);let tp_mode=tpMode.value;if(MI>=500&&ROI>=1){MV=0;if(tp_mode==="YY"){for(let i=1;i<=T*12;i++){let temp=MI*Math.pow(1+ROI/400,(4*i)/12);MV=Math.round(MV+temp);}
TI=MI*T*12;}else if(tp_mode==="MM"){for(let i=1;i<=T;i++){let temp=MI*Math.pow(1+ROI/400,(4*i)/12);MV=Math.round(MV+temp);}
TI=MI*T;}
ER=Math.round(MV-TI);O_TI.innerHTML="₹"+TI.toLocaleString('en-IN');O_ER.innerHTML="₹"+ER.toLocaleString('en-IN');O_MV.innerHTML="₹"+MV.toLocaleString('en-IN');if(!initialLoad){chart.destroy();}
DrawChart(TI,ER);initialLoad=false;}}
function DrawChart(TI,ER){var ctx=document.getElementById("myChart").getContext("2d");chart=new Chart(ctx,{type:"doughnut",data:{labels:["Total Investment","Total Interest"],datasets:[{backgroundColor:["#5367ff","#00d09c"],data:[TI,ER],},],},options:{segmentShowStroke:false,responsive:true,},});}
function getParams(){let urlVal=window.location.href;let url=new URL(urlVal);let cta=url.searchParams.get("cta");let name=url.searchParams.get("name");if(cta==="hide"){let ctaDiv=document.getElementById("cta");ctaDiv.style.display="none";}
if(name!==null){let heading=document.getElementById("heading");heading.innerHTML=name+" RD Calculator";}}
function AttachInputListeners(){tpMode.addEventListener("change",(e)=>{let val=e.target.value;if(val==="YY"){inputTenure.min="1";inputTenure.max="10";inputTenure.step="1";inputTenure.value="2";sliderTenure.min="1";sliderTenure.max="10";sliderTenure.step="1";sliderTenure.value="2";calculateIt();}else if(val==="MM"){inputTenure.value="6";sliderTenure.min="3";sliderTenure.max="9";sliderTenure.step="3";sliderTenure.value="6";calculateIt();}});inputMI.addEventListener("input",(e)=>{let val=e.target.value;if(val<0){inputMI.value=500;calculateIt();}
if(val>1000000){inputMI.value=1000000;calculateIt();}});inputROI.addEventListener("input",(e)=>{let val=e.target.value;if(val<0){inputROI.value=1;calculateIt();}
if(val>12){inputROI.value=12;calculateIt();}});}