"use strict";var sliderTI=document.getElementById("myTotalInvestmentAmount");var inputTI=document.getElementById("inputTotalInvestment");var sliderWPM=document.getElementById("myWithdrawalAmount");var inputWPM=document.getElementById("inputWithdrawalAmount");var sliderROI=document.getElementById("myExpectedReturns");var inputROI=document.getElementById("inputExpectedReturns");var sliderTenure=document.getElementById("myTenure");var inputTenure=document.getElementById("inputTenure");inputTI.innerHTML=sliderTI.value;inputROI.innerHTML=sliderROI.value;inputWPM.innerHTML=sliderWPM.value;inputTenure.innerHTML=sliderTenure.value;sliderTI.oninput=function(){inputTI.innerHTML=this.value;};sliderWPM.oninput=function(){inputWPM.innerHTML=this.value;};sliderROI.oninput=function(){inputROI.innerHTML=this.value;};sliderTenure.oninput=function(){inputTenure.innerHTML=this.value;};function showTotalInvestmentVal(newVal){sliderTI.value=newVal;calculateIt();}
function showWithdrawalVal(newVal){sliderWPM.value=newVal;calculateIt();}
function showExpectedReturnsVal(newVal){sliderROI.value=newVal;calculateIt();}
function showTenureVal(newVal){sliderTenure.value=newVal;calculateIt();}
sliderTI.addEventListener("input",updateValueTotalInvestment);sliderROI.addEventListener("input",updateValueExpectedReturns);sliderWPM.addEventListener("input",updateValueWithdrawalAmount);sliderTenure.addEventListener("input",updateValueTenure);function updateValueTotalInvestment(e){inputTI.value=e.srcElement.value;calculateIt();}
function updateValueWithdrawalAmount(e){inputWPM.value=e.srcElement.value;calculateIt();}
function updateValueExpectedReturns(e){inputROI.value=e.srcElement.value;calculateIt();}
function updateValueTenure(e){inputTenure.value=e.srcElement.value;calculateIt();}
AttachInputListeners();getParams();calculateIt();function calculateIt(){let O_TI=document.getElementById("r1");let O_TW=document.getElementById("r2");let O_FV=document.getElementById("r3");let TI=Number(inputTI.value);let WPM=Number(inputWPM.value);let ROI=Number(inputROI.value);let T=Number(inputTenure.value);let TW=WPM*T*12;if(TI>=10000&&WPM>=500&&ROI>=1){let FV=Math.round(TI*Math.pow(1+ROI/100,T)-(WPM*(Math.pow(1+(Math.pow(1+ROI/100,1/12)-1),T*12)-1))/(Math.pow(1+ROI/100,1/12)-1));O_TI.innerHTML="₹"+TI.toLocaleString('en-IN');O_TW.innerHTML="₹"+TW.toLocaleString('en-IN');O_FV.innerHTML="₹"+FV.toLocaleString('en-IN');}}
function getParams(){let urlVal=window.location.href;let url=new URL(urlVal);let cta=url.searchParams.get("cta");if(cta==="hide"){let ctaDiv=document.getElementById("cta");ctaDiv.style.display="none";}}
function AttachInputListeners(){inputTI.addEventListener("input",(e)=>{let val=Number(e.target.value);if(val<0){inputTI.value=10000;calculateIt();}
if(val>5000000){inputTI.value=5000000;calculateIt();}});inputWPM.addEventListener("input",(e)=>{let val=Number(e.target.value);if(val<0){inputWPM.value=500;calculateIt();}
if(val>50000){inputWPM.value=50000;calculateIt();}});inputROI.addEventListener("input",(e)=>{let val=Number(e.target.value);if(val<0){inputROI.value=1;calculateIt();}
if(val>30){inputROI.value=30;calculateIt();}});}