I have 12 years of experience in Java Spring boot and aws. I am working at Infosys. my current project is over and I got released from the project. for a new project, I have to go through a project interview. Kindly give the most probable question and answer related to advance java.
output: give markdown source with proper heading

I have 12 years of experience in Java Spring boot and aws. I am working at Infosys. 
my current project is over and I got released from the project. for a new project, I have to go through a project interview. Kindly give introduction the myself.
output: give markdown source with proper heading

Spring boot bean scope question and answer for 12 year software developer
output: give markdown source with proper heading

give 100 Advance Java question and very short answer for 12 year software developer
output: give markdown source with proper heading

give 100 Advance Microservice with spring boot question and very short answer for 12 year software developer
output: give markdown source with proper heading

give 10 Restful Webservice with spring boot question and very short answer for 12 year software developer
output: give markdown source with proper heading

I am working for a company as a java developer. I have to write Java 17 new features article in a very interesting way. explain "JEPS 306: Restore Always-Strict Floating-Point Semantics " with proper example so that any beginner can understand.
output: give markdown source with proper heading

Explain "JEPS 306: Restore Always-Strict Floating-Point Semantics " with proper example so that any beginner can understand.
output: give markdown source with proper heading

Explain "JEPS 410: Removal Experimental AOT and JIT Compiler " with proper example so that any beginner can understand.
output: give markdown source with proper heading

- 410: Removal Experimental AOT and JIT Compiler 
- 411: Deprecate the Security manager for Removal 
- 412: Foreign Functions & memory API(Incubator)
- 414: Vector API(Second Incubator)
- 415: Context-Specific Deserialization Filters  