"use strict";var amountSlider=document.getElementById("myAmount");var amountOutput=document.getElementById("inputAmount");var roiSlider=document.getElementById("myRoi");var roiOutput=document.getElementById("inputRoi");var yearSlider=document.getElementById("myYears");var yearOutput=document.getElementById("inputYears");amountOutput.value=amountSlider.value;roiOutput.value=roiSlider.value;yearOutput.value=yearSlider.value;amountSlider.oninput=function(){amountOutput.innerHTML=this.value;};roiSlider.oninput=function(){roiOutput.innerHTML=this.value;};yearSlider.oninput=function(){yearOutput.innerHTML=this.value;};function showValAmount(newVal){amountSlider.value=newVal;calculateIt();}
function showValRoi(newVal){roiSlider.value=newVal;calculateIt();}
function showValYears(newVal){yearSlider.value=newVal;calculateIt();}
amountSlider.addEventListener("input",updateValueAmount);roiSlider.addEventListener("input",updateValueRoi);yearSlider.addEventListener("input",updateValueYears);function updateValueAmount(e){amountOutput.value=e.srcElement.value;calculateIt();}
function updateValueRoi(e){roiOutput.value=e.srcElement.value;calculateIt();}
function updateValueYears(e){yearOutput.value=e.srcElement.value;calculateIt();}
AttachInputListeners();var initialLoad=true;var chart;getParams();calculateIt();function calculateIt(){var monthlyEMI=document.getElementById("r1");var pricipalAmount=document.getElementById("r2");var totalInterest=document.getElementById("r3");var totalAmount=document.getElementById("r4");var A,R,N;A=Number(amountOutput.value);R=Number(roiOutput.value);N=Number(yearOutput.value);if(A>=1000&&R>=1){let n=N*12;let i=R/(100*12);var monthlyEMIval=Math.round(A*i*(Math.pow(1+i,n)/(Math.pow(1+i,n)-1)));var totalInterestVal=monthlyEMIval*N*12-A;var totalAmountVal=monthlyEMIval*N*12;monthlyEMI.innerHTML="₹"+monthlyEMIval.toLocaleString('en-IN');pricipalAmount.innerHTML="₹"+A.toLocaleString('en-IN');totalInterest.innerHTML="₹"+totalInterestVal.toLocaleString('en-IN');totalAmount.innerHTML="₹"+totalAmountVal.toLocaleString('en-IN');if(!initialLoad){chart.destroy();}
DrawChart(A,totalInterestVal);initialLoad=false;}}
function DrawChart(A,totalInterestVal){var ctx=document.getElementById("myChart").getContext("2d");chart=new Chart(ctx,{type:"doughnut",data:{labels:["Principal Amount","Interest Amount"],datasets:[{backgroundColor:["#5367ff","#00d09c"],data:[A,totalInterestVal],},],},options:{segmentShowStroke:false,responsive:true,},});}
function getParams(){let urlVal=window.location.href;let url=new URL(urlVal);let type=url.searchParams.get("type");let name=url.searchParams.get("name");let cta=url.searchParams.get("cta");let logo=url.searchParams.get("logo");let heading=document.getElementById("heading");if(type==="home"){amountOutput.value="2500000";roiOutput.value="7.25";yearOutput.value="20";if(name!==null){heading.innerHTML=name+" Home Loan EMI Calculator";}else{heading.innerHTML="Home Loan EMI Calculator";}}else if(type==="car"){amountOutput.value="1000000";roiOutput.value="9.5";yearOutput.value="7";if(name!==null){heading.innerHTML=name+" Car Loan EMI Calculator";}else{heading.innerHTML="Car Loan EMI Calculator";}}else if(type==="personal"){amountOutput.value="500000";roiOutput.value="13.5";yearOutput.value="5";if(name!==null){heading.innerHTML=name+" Personal Loan EMI Calculator";}else{heading.innerHTML="Personal Loan EMI Calculator";}}else{if(name!==null){heading.innerHTML=name+" EMI Calculator";}else{heading.innerHTML="EMI Calculator";}}
if(cta==="hide"){let ctaDiv=document.getElementById("cta");ctaDiv.style.display="none";}
if(logo==="true"){document.getElementById("logo").style.display="block";}}
function AttachInputListeners(){amountOutput.addEventListener("input",(e)=>{let val=Number(e.target.value);if(val<0){amountOutput.value=1000;calculateIt();}
if(val>10000000){amountOutput.value=10000000;calculateIt();}});roiOutput.addEventListener("input",(e)=>{let val=Number(e.target.value);if(val<0){roiOutput.value=1;calculateIt();}
if(val>30){roiOutput.value=30;calculateIt();}});}